# Generated by Django 3.0.1 on 2020-02-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarriersProducts',
            fields=[
                ('pk_products', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nroempresa', models.IntegerField(verbose_name='Empresa')),
                ('nrocarga', models.IntegerField(verbose_name='Carga')),
                ('seqlote', models.IntegerField(verbose_name='Lote')),
                ('seqtarefa', models.IntegerField(blank=True, null=True, verbose_name='Tarefa')),
                ('seqatividade', models.IntegerField(verbose_name='Aitividade')),
                ('seqproduto', models.IntegerField(verbose_name='Produto')),
                ('desccompleta', models.CharField(max_length=100, verbose_name='Descrição')),
                ('descreduzida', models.CharField(max_length=50, verbose_name='Descrição')),
                ('codrua', models.CharField(max_length=3, verbose_name='Rua')),
                ('nropredio', models.SmallIntegerField(verbose_name='Prédio')),
                ('nroapartamento', models.SmallIntegerField(verbose_name='Nível')),
                ('nrosala', models.SmallIntegerField(verbose_name='Local')),
                ('especieendereco', models.CharField(choices=[('A', 'Grandeza'), ('M', 'Miudeza')], max_length=1, verbose_name='Tipo End.')),
                ('indterreoaereo', models.CharField(choices=[('T', 'Térreo'), ('A', 'Aéreo')], max_length=1, verbose_name='Tipo Local')),
                ('qtdembalagem', models.FloatField(verbose_name='Qtd. Embalagem')),
                ('qtdatual', models.FloatField(verbose_name='Qtd. Atual')),
                ('statusendereco', models.CharField(choices=[('D', 'Disponível'), ('O', 'Ocupado'), ('B', 'Bloqueado'), ('R', 'Reservado'), ('I', 'Inativo'), ('E', 'Restrito'), ('Q', 'Quarentena')], max_length=1, verbose_name='Tipo Local')),
                ('tipespecie', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Espécie')),
                ('coddepossepar', models.SmallIntegerField(verbose_name='Depós. Separ.')),
                ('destino', models.CharField(max_length=40, verbose_name='Destino')),
                ('tipentrega', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Entrega')),
                ('mcubtotal', models.FloatField(verbose_name='Cubagem')),
                ('pesototal', models.FloatField(verbose_name='Peso')),
                ('nrobox', models.SmallIntegerField(verbose_name='Box do Lote')),
                ('statuscarga', models.CharField(choices=[('A', 'Aguardando'), ('F', 'Faturada'), ('G', 'Gerada'), ('L', 'Liberada'), ('S', 'Em Separação'), ('T', 'Termo de Liberação'), ('C', 'Gerando Carregamento'), ('X', 'Iniciado Processo de Cancelamento da Carga')], max_length=1, verbose_name='Status da Carga')),
                ('valorcarga', models.FloatField(verbose_name='Valor da Carga')),
                ('qtdembcargasep', models.FloatField(verbose_name='Qtd. Emb. Separ.')),
                ('qtdcontada', models.FloatField(verbose_name='Qtd. Emb. Contada')),
                ('qtdembsolcargasep', models.FloatField(verbose_name='Qtd. Emb. Carga Solic.')),
                ('qtdembsepcargasep', models.FloatField(verbose_name='Qtd. Emb. Carga Separ.')),
                ('codtipatividade', models.CharField(max_length=2, verbose_name='Código Atividade')),
                ('nroquebra', models.SmallIntegerField(verbose_name='Quebra')),
                ('mesano', models.CharField(blank=True, max_length=5, null=True, verbose_name='Mês/Ano')),
                ('peso', models.FloatField(verbose_name='Peso.')),
                ('metragemcubica', models.FloatField(verbose_name='Cubagem')),
                ('qtdvolume', models.FloatField(verbose_name='Volumnes')),
                ('qtditem', models.FloatField(verbose_name='Items')),
                ('indexclusao', models.CharField(max_length=1, verbose_name='Excluído')),
                ('grauprioridade', models.IntegerField(verbose_name='Prioridade')),
                ('statusrf', models.CharField(blank=True, max_length=1, null=True, verbose_name='Status RF')),
                ('statusatividade', models.CharField(choices=[('A', 'Aguardando'), ('E', 'Em Execução'), ('X', 'Cancelada'), ('F', 'Finalizada')], max_length=1, verbose_name='Status da Atividade')),
                ('tipseparacao', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Serpação')),
                ('tiplote', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Lote')),
                ('pesototallote', models.FloatField(verbose_name='Peso Lote')),
                ('mcubtotallote', models.FloatField(verbose_name='Cubagem Lote')),
                ('qtdvolumelote', models.FloatField(verbose_name='Valumes Lote')),
                ('qtditemlote', models.FloatField(verbose_name='Items do Lote')),
                ('seqordenacaoseparacao', models.IntegerField(verbose_name='Ordem Separação')),
                ('seqpessoa', models.IntegerField(verbose_name='Código Cliente')),
                ('qtdembsolcarga', models.FloatField(verbose_name='Qtd. Emb. Solic.')),
                ('qtdembcarga', models.FloatField(verbose_name='Qtd. Emb.')),
                ('qtdembsepcarga', models.FloatField(verbose_name='Qtd. Emb. Separada')),
                ('nropedvenda', models.IntegerField(blank=True, null=True, verbose_name='Número Pedido')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data')),
            ],
            options={
                'db_table': 'cargo_products',
            },
        ),
        migrations.CreateModel(
            name='LastProductCharge',
            fields=[
                ('pk_product_last_charge', models.SmallIntegerField(default=1, primary_key=True, serialize=False, verbose_name='código')),
                ('last_charge', models.DateTimeField(auto_now=True, verbose_name='Última Carga')),
            ],
            options={
                'db_table': 'product_last_charge',
            },
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('pk_user_products', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Usuario/Carga')),
                ('charge', models.IntegerField(verbose_name='Num. Carga')),
                ('lot', models.IntegerField(verbose_name='Num Lote')),
                ('street', models.CharField(max_length=3, verbose_name='Rua')),
                ('tower', models.CharField(max_length=5, verbose_name='Predio')),
                ('level', models.CharField(max_length=3, verbose_name='Nivel')),
                ('position', models.CharField(max_length=5, verbose_name='Posicao')),
                ('description', models.CharField(max_length=50, verbose_name='Descricao')),
                ('stock', models.FloatField(verbose_name='Estoque Atual')),
                ('qtd_packing', models.FloatField(verbose_name='Quant. da Embalagem')),
                ('qtd_order', models.FloatField(verbose_name='QUant. do Pedido')),
                ('qtd_selected', models.FloatField(verbose_name='Quant. Coletada')),
                ('pk_customer', models.IntegerField(blank=True, default=0, verbose_name='Cod. Cliente')),
                ('unity', models.CharField(max_length=2, verbose_name='UN')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('volume', models.FloatField(verbose_name='Volume m3')),
                ('side', models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='E', max_length=1, verbose_name='Lado')),
                ('flag_ready', models.SmallIntegerField(default=0, verbose_name='carregado')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data de Insercao')),
            ],
            options={
                'db_table': 'user_products',
            },
        ),
        migrations.CreateModel(
            name='CarriersProductsCars',
            fields=[
                ('pk_products_cars', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Box')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('fk_carriers_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.CarriersProducts', verbose_name='Produto')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro')),
                ('fk_cars_boxes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.CarsBoxes', verbose_name='Box')),
            ],
            options={
                'db_table': 'carriers_products_cars',
            },
        ),
    ]
