# Generated by Django 3.0.1 on 2020-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersproducts',
            name='mcubtotal',
            field=models.FloatField(verbose_name='Cubagem'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='mcubtotallote',
            field=models.FloatField(verbose_name='Cubagem Lote'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='metragemcubica',
            field=models.FloatField(verbose_name='Cubagem'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='peso',
            field=models.FloatField(verbose_name='Peso.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='pesototal',
            field=models.FloatField(verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='pesototallote',
            field=models.FloatField(verbose_name='Peso Lote'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdatual',
            field=models.FloatField(verbose_name='Qtd. Atual'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdcontada',
            field=models.FloatField(verbose_name='Qtd. Emb. Contada'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembalagem',
            field=models.FloatField(verbose_name='Qtd. Embalagem'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembcarga',
            field=models.FloatField(verbose_name='Qtd. Emb.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembcargasep',
            field=models.FloatField(verbose_name='Qtd. Emb. Separ.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembsepcarga',
            field=models.FloatField(verbose_name='Qtd. Emb. Separada'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembsepcargasep',
            field=models.FloatField(verbose_name='Qtd. Emb. Carga Separ.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembsolcarga',
            field=models.FloatField(verbose_name='Qtd. Emb. Solic.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdembsolcargasep',
            field=models.FloatField(verbose_name='Qtd. Emb. Carga Solic.'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtditemlote',
            field=models.FloatField(verbose_name='Items do Lote'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='qtdvolumelote',
            field=models.FloatField(verbose_name='Valumes Lote'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='valorcarga',
            field=models.FloatField(verbose_name='Valor da Carga'),
        ),
    ]
