# Generated by Django 3.0.1 on 2020-03-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200303_1205'),
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarriersCars',
            fields=[
                ('pk_carriers_cars', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Usuario/Carga')),
                ('fk_customer', models.IntegerField(blank=True, default=0, verbose_name='Cod. Cliente')),
                ('charge', models.IntegerField(verbose_name='Num. Carga')),
                ('lot', models.IntegerField(verbose_name='Num Lote')),
                ('street', models.CharField(max_length=3, verbose_name='Rua')),
                ('tower', models.CharField(max_length=5, verbose_name='Predio')),
                ('level', models.CharField(max_length=3, verbose_name='Nivel')),
                ('position', models.CharField(max_length=5, verbose_name='Posicao')),
                ('stock', models.FloatField(verbose_name='Estoque Atual')),
                ('qtd_packing', models.FloatField(verbose_name='Quant. da Embalagem')),
                ('qtd_order', models.FloatField(verbose_name='Quant. do Pedido')),
                ('qtd_collected', models.FloatField(verbose_name='Quant. Coletada')),
                ('unity', models.CharField(max_length=2, verbose_name='UN')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('volume', models.FloatField(verbose_name='Volume m3')),
                ('weight_box', models.FloatField(verbose_name='Peso do Box')),
                ('volume_box', models.FloatField(verbose_name='Volume do Box')),
                ('side', models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='E', max_length=1, verbose_name='Lado')),
                ('flag_status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('flag_ready', models.SmallIntegerField(default=0, verbose_name='Carregado')),
                ('flag_conference', models.SmallIntegerField(default=0, verbose_name='Conferido')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data de Insercao')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro')),
                ('fk_cars_boxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CarsBoxes', verbose_name='Box')),
            ],
            options={
                'db_table': 'carrier_products',
            },
        ),
        migrations.CreateModel(
            name='LastCharge',
            fields=[
                ('pk_last_charge', models.SmallIntegerField(default=1, primary_key=True, serialize=False, verbose_name='Código da Carga')),
                ('date_last_charge', models.DateTimeField(auto_now=True, verbose_name='Data da Carga')),
            ],
            options={
                'db_table': 'app_last_charge',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pk_products', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_prod', models.CharField(max_length=50, verbose_name='Descrição')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('unity', models.CharField(max_length=5, verbose_name='Unidade')),
                ('qtd_unity', models.FloatField(verbose_name='QUant. da Unidade')),
                ('image_prod', models.TextField(blank=True, null=True, verbose_name='Imagem')),
            ],
        ),
        migrations.RemoveField(
            model_name='carriersproductscars',
            name='fk_carriers_products',
        ),
        migrations.RemoveField(
            model_name='carriersproductscars',
            name='fk_cars',
        ),
        migrations.RemoveField(
            model_name='carriersproductscars',
            name='fk_cars_boxes',
        ),
        migrations.DeleteModel(
            name='LastProductCharge',
        ),
        migrations.DeleteModel(
            name='UserProducts',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='pk_products',
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='pk_carriers_products',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='CarriersProductsCars',
        ),
        migrations.AddField(
            model_name='carrierscars',
            name='fk_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carriers.CarriersProducts', verbose_name='Produto'),
        ),
    ]
