# Generated by Django 3.0.1 on 2020-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_auto_20200303_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierscars',
            name='flag_status',
            field=models.CharField(choices=[('L', 'Livre'), ('P', 'Processando'), ('S', 'Em Separação'), ('C', 'Em Conferência')], default='L', max_length=1, verbose_name='Status'),
        ),
    ]
