# Generated by Django 3.0.1 on 2020-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_auto_20200217_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersproducts',
            name='seqtarefa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarefa'),
        ),
    ]
