# Generated by Django 3.0.1 on 2020-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_auto_20200217_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersproducts',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso.'),
        ),
    ]
