# Generated by Django 3.0.1 on 2020-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_auto_20200305_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcharge',
            name='fk_company',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lastcharge',
            name='fk_customer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AddField(
            model_name='lastcharge',
            name='fk_product',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='lastcharge',
            name='num_lot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='pk_carriers_products',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='lastcharge',
            name='date_last_charge',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Carga'),
        ),
    ]
