# Generated by Django 3.0.1 on 2020-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0004_auto_20200305_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersproducts',
            name='peso',
            field=models.FloatField(default=0.0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='status',
            field=models.CharField(default='L', max_length=1, verbose_name='Status'),
        ),
    ]
