# Generated by Django 3.0.1 on 2020-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0005_auto_20200217_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProductCharge',
            fields=[
                ('pk_product_last_charge', models.SmallIntegerField(default=1, primary_key=True, serialize=False, verbose_name='código')),
                ('last_charge', models.DateTimeField(auto_now=True, verbose_name='Última Carga')),
            ],
            options={
                'db_table': 'product_last_charge',
            },
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('pk_user_products', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Usuario/Carga')),
                ('charge', models.IntegerField(verbose_name='Num. Carga')),
                ('lot', models.IntegerField(verbose_name='Num Lote')),
                ('street', models.CharField(max_length=3, verbose_name='Rua')),
                ('tower', models.CharField(max_length=5, verbose_name='Predio')),
                ('level', models.CharField(max_length=3, verbose_name='Nivel')),
                ('position', models.CharField(max_length=5, verbose_name='Posicao')),
                ('description', models.CharField(max_length=50, verbose_name='Descricao')),
                ('stock', models.FloatField(verbose_name='Estoque Atual')),
                ('qtd_packing', models.FloatField(verbose_name='Quant. da Embalagem')),
                ('qtd_order', models.FloatField(verbose_name='QUant. do Pedido')),
                ('qtd_selected', models.FloatField(verbose_name='Quant. Coletada')),
                ('pk_order', models.IntegerField(verbose_name='Num. Pedido')),
                ('unity', models.CharField(max_length=2, verbose_name='UN')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('volume', models.FloatField(verbose_name='Volume m3')),
                ('flag_ready', models.SmallIntegerField(default=0, verbose_name='carregado')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data de Insercao')),
            ],
            options={
                'db_table': 'user_products',
            },
        ),
    ]
