# Generated by Django 3.0.1 on 2020-03-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0005_auto_20200305_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriersproducts',
            name='peso',
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='altura',
            field=models.FloatField(default=0.0, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='embalagem',
            field=models.CharField(default='', max_length=5, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='largura',
            field=models.FloatField(default=0.0, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='pesobruto',
            field=models.FloatField(default=0.0, verbose_name='Peso Bruto'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='pesoliquido',
            field=models.FloatField(default=0.0, verbose_name='Peso Líquido'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='profundidade',
            field=models.FloatField(default=0.0, verbose_name='Profundidade'),
        ),
    ]
