# Generated by Django 3.0.1 on 2020-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0006_lastproductcharge_userproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='pk_order',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='pk_customer',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cod. Cliente'),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='side',
            field=models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='E', max_length=1, verbose_name='Lado'),
        ),
    ]
