# Generated by Django 3.0.1 on 2020-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0006_auto_20200305_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriersproducts',
            name='peso',
            field=models.FloatField(default=0.0, verbose_name='Peso??'),
        ),
    ]
