# Generated by Django 3.0.1 on 2020-03-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0008_auto_20200305_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrierscars',
            options={'verbose_name_plural': 'Carga Produtos'},
        ),
        migrations.AlterModelOptions(
            name='carriersproducts',
            options={'verbose_name_plural': 'Carga Original'},
        ),
        migrations.AlterModelOptions(
            name='lastcharge',
            options={'verbose_name_plural': 'Última Carga'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelTable(
            name='carriersproducts',
            table='interface_charge',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
