# Generated by Django 3.0.1 on 2020-03-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20200306_0828'),
        ('carriers', '0010_auto_20200306_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargasProdutos',
            fields=[
                ('pk_cargas_produtos', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Acesso')),
                ('nroempresa', models.IntegerField(verbose_name='Empresa')),
                ('nrocarga', models.IntegerField(verbose_name='Carga')),
                ('seqlote', models.IntegerField(verbose_name='Lote')),
                ('seqtarefa', models.IntegerField(blank=True, null=True, verbose_name='Tarefa')),
                ('seqatividade', models.IntegerField(verbose_name='Aitividade')),
                ('seqproduto', models.IntegerField(verbose_name='Produto')),
                ('desccompleta', models.CharField(max_length=100, verbose_name='Descrição')),
                ('descreduzida', models.CharField(max_length=50, verbose_name='Descrição')),
                ('codrua', models.CharField(max_length=3, verbose_name='Rua')),
                ('nropredio', models.SmallIntegerField(verbose_name='Prédio')),
                ('nroapartamento', models.SmallIntegerField(verbose_name='Nível')),
                ('nrosala', models.SmallIntegerField(verbose_name='Local')),
                ('especieendereco', models.CharField(choices=[('A', 'Grandeza'), ('M', 'Miudeza')], max_length=1, verbose_name='Tipo End.')),
                ('indterreoaereo', models.CharField(choices=[('T', 'Térreo'), ('A', 'Aéreo')], max_length=1, verbose_name='Tipo Local')),
                ('qtdembalagem', models.FloatField(default=0.0, verbose_name='Qtd. Embalagem')),
                ('qtdatual', models.FloatField(default=0.0, verbose_name='Qtd. Atual')),
                ('statusendereco', models.CharField(choices=[('D', 'Disponível'), ('O', 'Ocupado'), ('B', 'Bloqueado'), ('R', 'Reservado'), ('I', 'Inativo'), ('E', 'Restrito'), ('Q', 'Quarentena')], max_length=1, verbose_name='Tipo Local')),
                ('tipespecie', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Espécie')),
                ('coddepossepar', models.SmallIntegerField(verbose_name='Depós. Separ.')),
                ('destino', models.CharField(max_length=40, verbose_name='Destino')),
                ('tipentrega', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Entrega')),
                ('mcubtotal', models.FloatField(default=0.0, verbose_name='Cubagem')),
                ('pesototal', models.FloatField(default=0.0, verbose_name='Peso')),
                ('nrobox', models.SmallIntegerField(verbose_name='Box do Lote')),
                ('statuscarga', models.CharField(choices=[('A', 'Aguardando'), ('F', 'Faturada'), ('G', 'Gerada'), ('L', 'Liberada'), ('S', 'Em Separação'), ('T', 'Termo de Liberação'), ('C', 'Gerando Carregamento'), ('X', 'Iniciado Processo de Cancelamento da Carga')], max_length=1, verbose_name='Status da Carga')),
                ('valorcarga', models.FloatField(default=0.0, verbose_name='Valor da Carga')),
                ('qtdembcargasep', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Separ.')),
                ('qtdcontada', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Contada')),
                ('qtdembsolcargasep', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Carga Solic.')),
                ('qtdembsepcargasep', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Carga Separ.')),
                ('codtipatividade', models.CharField(max_length=2, verbose_name='Código Atividade')),
                ('nroquebra', models.SmallIntegerField(verbose_name='Quebra')),
                ('mesano', models.CharField(blank=True, max_length=5, null=True, verbose_name='Mês/Ano')),
                ('metragemcubica', models.FloatField(default=0.0, verbose_name='Cubagem')),
                ('qtdvolume', models.FloatField(default=0.0, verbose_name='Volumnes')),
                ('qtditem', models.FloatField(default=0.0, verbose_name='Items')),
                ('indexclusao', models.CharField(max_length=1, verbose_name='Excluído')),
                ('grauprioridade', models.IntegerField(verbose_name='Prioridade')),
                ('statusrf', models.CharField(blank=True, max_length=1, null=True, verbose_name='Status RF')),
                ('statusatividade', models.CharField(choices=[('A', 'Aguardando'), ('E', 'Em Execução'), ('X', 'Cancelada'), ('F', 'Finalizada')], max_length=1, verbose_name='Status da Atividade')),
                ('tipseparacao', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Serpação')),
                ('tiplote', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Lote')),
                ('pesototallote', models.FloatField(default=0.0, verbose_name='Peso Lote')),
                ('mcubtotallote', models.FloatField(default=0.0, verbose_name='Cubagem Lote')),
                ('qtdvolumelote', models.FloatField(default=0.0, verbose_name='Valumes Lote')),
                ('qtditemlote', models.FloatField(default=0.0, verbose_name='Items do Lote')),
                ('seqordenacaoseparacao', models.IntegerField(verbose_name='Ordem Separação')),
                ('seqpessoa', models.IntegerField(verbose_name='Código Cliente')),
                ('qtdembsolcarga', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Solic.')),
                ('qtdembcarga', models.FloatField(default=0.0, verbose_name='Qtd. Emb.')),
                ('qtdembsepcarga', models.FloatField(default=0.0, verbose_name='Qtd. Emb. Separada')),
                ('nropedvenda', models.IntegerField(blank=True, null=True, verbose_name='Número Pedido')),
                ('embalagem', models.CharField(default='', max_length=5, verbose_name='Unidade')),
                ('peso', models.FloatField(default=0.0, verbose_name='Peso??')),
                ('pesobruto', models.FloatField(default=0.0, verbose_name='Peso Bruto')),
                ('pesoliquido', models.FloatField(default=0.0, verbose_name='Peso Líquido')),
                ('altura', models.FloatField(default=0.0, verbose_name='Altura')),
                ('largura', models.FloatField(default=0.0, verbose_name='Largura')),
                ('profundidade', models.FloatField(default=0.0, verbose_name='Profundidade')),
                ('status', models.CharField(default='L', max_length=1, verbose_name='Status')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data')),
            ],
            options={
                'verbose_name_plural': 'ConsincoCargas',
                'db_table': 'consinco_cargas',
            },
        ),
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('pk_carriers', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Código Pedido')),
                ('fk_customer', models.IntegerField(blank=True, default=0, verbose_name='Cod. Cliente')),
                ('charge', models.IntegerField(verbose_name='Num. Carga')),
                ('lot', models.IntegerField(verbose_name='Num Lote')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('volume', models.FloatField(verbose_name='Volume m3')),
                ('flag_status', models.CharField(choices=[('L', 'Livre'), ('P', 'Processando'), ('S', 'Em Separação'), ('C', 'Em Conferência')], default='L', max_length=1, verbose_name='Status')),
                ('flag_ready', models.SmallIntegerField(default=0, verbose_name='Carregado')),
                ('flag_conference', models.SmallIntegerField(default=0, verbose_name='Conferido')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data de Insercao')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'icity_carriers',
            },
        ),
        migrations.CreateModel(
            name='CarriersBoxes',
            fields=[
                ('pk_carriers_boxes', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Box do Prod. Pedido')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('volume', models.FloatField(verbose_name='Volume m3')),
            ],
            options={
                'verbose_name_plural': 'Boxes dos Pedidos',
                'db_table': 'icity_carriers_boxes',
            },
        ),
        migrations.CreateModel(
            name='ProductsSimilar',
            fields=[
                ('pk_products_similar', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Código de Barras')),
                ('street', models.CharField(max_length=3, verbose_name='Rua')),
                ('tower', models.CharField(max_length=5, verbose_name='Predio')),
                ('level', models.CharField(max_length=3, verbose_name='Nivel')),
                ('position', models.CharField(max_length=5, verbose_name='Posicao')),
                ('unity', models.CharField(max_length=5, verbose_name='Unidade')),
                ('qtd_unity', models.FloatField(verbose_name='QUant. da Unidade')),
                ('image_prod', models.TextField(blank=True, null=True, verbose_name='Imagem')),
            ],
            options={
                'verbose_name_plural': 'Produtos Similares',
                'db_table': 'icity_products_similarity',
            },
        ),
        migrations.AlterModelOptions(
            name='carriersproducts',
            options={'verbose_name_plural': 'Produtos dos Pedidos'},
        ),
        migrations.RenameField(
            model_name='carriersproducts',
            old_name='pesototal',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='coddepossepar',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='codrua',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='codtipatividade',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='desccompleta',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='descreduzida',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='embalagem',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='especieendereco',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='grauprioridade',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='indexclusao',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='indterreoaereo',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='insert_date',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='mcubtotal',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='mcubtotallote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='mesano',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='metragemcubica',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nroapartamento',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nrobox',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nrocarga',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nroempresa',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nropedvenda',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nropredio',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nroquebra',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='nrosala',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='pesobruto',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='pesoliquido',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='pesototallote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='profundidade',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdatual',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdcontada',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembalagem',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembcarga',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembcargasep',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembsepcarga',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembsepcargasep',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembsolcarga',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdembsolcargasep',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtditem',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtditemlote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdvolume',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='qtdvolumelote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqatividade',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqlote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqordenacaoseparacao',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqpessoa',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqproduto',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='seqtarefa',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='status',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='statusatividade',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='statuscarga',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='statusendereco',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='statusrf',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='tipentrega',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='tipespecie',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='tiplote',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='tipseparacao',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='valorcarga',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_prod',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qtd_unity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unity',
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='fk_products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='carriers.Products', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='level',
            field=models.CharField(default=1, max_length=3, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='position',
            field=models.CharField(default=0, max_length=5, verbose_name='Posicao'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='qtd_collected',
            field=models.FloatField(default=0.0, verbose_name='Quant. Coletada'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='qtd_order',
            field=models.FloatField(default=0.0, verbose_name='Quant. do Pedido'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='qtd_packing',
            field=models.FloatField(default=0.0, verbose_name='Quant. da Embalagem'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='side',
            field=models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='E', max_length=1, verbose_name='Lado'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='stock',
            field=models.FloatField(default=0.0, verbose_name='Estoque Atual'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='street',
            field=models.CharField(default='', max_length=3, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='tower',
            field=models.CharField(default='', max_length=5, verbose_name='Predio'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='unity',
            field=models.CharField(default='', max_length=2, verbose_name='UN'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='volume',
            field=models.FloatField(default=0.0, verbose_name='Volume m3'),
        ),
        migrations.AddField(
            model_name='products',
            name='depth',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Profundidade'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Largura'),
        ),
        migrations.AlterField(
            model_name='carriersproducts',
            name='pk_carriers_products',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Produtos do Pedido'),
        ),
        migrations.AlterModelTable(
            name='carriersproducts',
            table='icity_carriers_products',
        ),
        migrations.AlterModelTable(
            name='lastcharge',
            table='icity_last_charge',
        ),
        migrations.AlterModelTable(
            name='products',
            table='icity_products',
        ),
        migrations.DeleteModel(
            name='CarriersCars',
        ),
        migrations.AddField(
            model_name='productssimilar',
            name='fk_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Products', verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='carriersboxes',
            name='fk_carriers_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carriers.CarriersProducts', verbose_name='Carga'),
        ),
        migrations.AddField(
            model_name='carriersboxes',
            name='fk_cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro'),
        ),
        migrations.AddField(
            model_name='carriersboxes',
            name='fk_cars_boxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.CarsBoxes', verbose_name='Box'),
        ),
        migrations.AddField(
            model_name='carriersboxes',
            name='fk_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='fk_carriers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='carriers.Carriers', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='fk_products_similar',
            field=models.ForeignKey(blank=True, max_length=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='carriers.ProductsSimilar', verbose_name='Código de Barras'),
        ),
    ]
