# Generated by Django 3.0.1 on 2020-03-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0011_auto_20200308_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcharge',
            name='fk_cargas_produtos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carriers.CargasProdutos', verbose_name='Cargas'),
        ),
    ]
