# Generated by Django 3.0.1 on 2020-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0013_auto_20200309_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carriers',
            old_name='volume',
            new_name='volume_charge',
        ),
        migrations.RenameField(
            model_name='carriers',
            old_name='weight',
            new_name='weight_charge',
        ),
        migrations.RenameField(
            model_name='carriersboxes',
            old_name='volume',
            new_name='volume_box',
        ),
        migrations.RenameField(
            model_name='carriersboxes',
            old_name='weight',
            new_name='weight_box',
        ),
        migrations.RenameField(
            model_name='carriersproducts',
            old_name='weight',
            new_name='weight_prod',
        ),
        migrations.RemoveField(
            model_name='carriersproducts',
            name='volume',
        ),
        migrations.AddField(
            model_name='carriersproducts',
            name='volume_prod',
            field=models.FloatField(default=0.0, verbose_name='Volume'),
        ),
    ]
