# Generated by Django 3.0.1 on 2020-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0014_auto_20200309_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='Data Inclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='cargasprodutos',
            name='tipseparacao',
            field=models.CharField(blank=True, choices=[('AG', 'Alimetício Grandeza'), ('BF', 'Fardarias Grandeza'), ('BG', 'Bebidas Grandeza'), ('CO', 'Confinado'), ('FA', 'Fracionado Alimento'), ('FB', 'Fracionado Bebidas'), ('FF', 'Leveza Papel Higiênico'), ('FR', 'Fracionado Alimento'), ('FG', 'Fracionado Gerais'), ('FL', 'Leveza Fardaria Grandeza'), ('LA', 'Licitação Alimento'), ('LF', 'Limpeza Fracionada'), ('LG', 'Limpeza Grandeza'), ('LL', 'Leveza Limpeza Grandeza')], max_length=2, null=True, verbose_name='Tipo Serpação'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='flag_type_line',
            field=models.CharField(choices=[('AG', 'Alimetício Grandeza'), ('BF', 'Fardarias Grandeza'), ('BG', 'Bebidas Grandeza'), ('CO', 'Confinado'), ('FA', 'Fracionado Alimento'), ('FB', 'Fracionado Bebidas'), ('FF', 'Leveza Papel Higiênico'), ('FG', 'Fracionados Gerais'), ('FR', 'Fracionado Geral'), ('FL', 'Leveza Fardaria Grandeza'), ('LA', 'Licitação Alimento'), ('LF', 'Limpeza Fracionada'), ('LG', 'Limpeza Grandeza'), ('LL', 'Leveza Limpeza Grandeza')], default='FG', max_length=2, verbose_name='Tipo Separação'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Insercao'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='volume_charge',
            field=models.FloatField(default=0.0, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='weight_charge',
            field=models.FloatField(default=0.0, verbose_name='Peso'),
        ),
    ]
