# Generated by Django 3.0.1 on 2020-03-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHosts',
            fields=[
                ('pk_api_hosts', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_host', models.CharField(max_length=50, verbose_name='Descrição')),
                ('type_net', models.SmallIntegerField(choices=[(0, 'LAN'), (1, 'WAN')], default=0, verbose_name='Tipo NET')),
                ('address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP')),
                ('port', models.IntegerField(default=5180, verbose_name='Porta')),
                ('flag_active', models.SmallIntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=0, verbose_name='Ativo')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data Inserção')),
            ],
            options={
                'verbose_name_plural': 'hosts',
                'db_table': 'icity_hosts',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('pk_cars', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('dsc_car', models.CharField(max_length=50, verbose_name='Descrição')),
                ('factory_serial', models.CharField(max_length=64, verbose_name='Núm. Serial')),
                ('date_factory', models.DateTimeField(verbose_name='Data Fabr.')),
                ('date_insert', models.DateTimeField(auto_now=True, verbose_name='Data Inserção')),
            ],
            options={
                'verbose_name_plural': 'Carros',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarsBoxes',
            fields=[
                ('pk_carsboxes', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Identificação')),
                ('box_name', models.CharField(max_length=30, verbose_name='Nome do Box')),
                ('fisical_box_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Caçamba')),
                ('level', models.SmallIntegerField(verbose_name='Nível')),
                ('box', models.SmallIntegerField(verbose_name='Box')),
                ('charge_key', models.TextField(blank=True, null=True, verbose_name='Carga Vinculada')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Peso Máx.')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Volume Máx.')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cars', verbose_name='Carro')),
            ],
            options={
                'verbose_name_plural': 'Boxes',
                'db_table': 'cars_boxes',
            },
        ),
        migrations.CreateModel(
            name='CarBoxesMessage',
            fields=[
                ('pk_car_boxes_message', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('flag_captured', models.SmallIntegerField(default=0, verbose_name='Capturado')),
                ('box_type_command', models.CharField(max_length=30, verbose_name='Tipo de Comando')),
                ('box_name', models.CharField(max_length=3, verbose_name='Nomeclatura')),
                ('box_message', models.TextField(verbose_name='Mensagem')),
                ('capture_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Captura')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Edicao')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data Insercao')),
                ('fk_car_boxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CarsBoxes', verbose_name='Box')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'db_table': 'cars_boxes_message',
            },
        ),
    ]
