# Generated by Django 3.0.1 on 2020-02-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('pk_cars', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('dsc_car', models.CharField(max_length=50, verbose_name='Descrição')),
                ('factory_serial', models.CharField(max_length=64, verbose_name='Núm. Serial')),
                ('date_factory', models.DateTimeField(verbose_name='Data Fabr.')),
                ('date_insert', models.DateTimeField(auto_now=True, verbose_name='Data Inserção')),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarsBoxes',
            fields=[
                ('pk_carsboxes', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('box_name', models.CharField(max_length=30, verbose_name='Código do Box')),
                ('fisical_box_id', models.CharField(max_length=20, verbose_name='Código da Caçamba')),
                ('level', models.SmallIntegerField(verbose_name='Nível')),
                ('box', models.SmallIntegerField(verbose_name='Box')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Peso')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Volume')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cars', verbose_name='Carro')),
            ],
            options={
                'verbose_name_plural': 'CarsBoxes',
                'db_table': 'cars_boxes',
            },
        ),
        migrations.CreateModel(
            name='CarBoxesMessage',
            fields=[
                ('pk_car_boxes_message', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('flag_captured', models.SmallIntegerField(default=0, verbose_name='Capturado')),
                ('box_type_command', models.CharField(max_length=30, verbose_name='Tipo de Comando')),
                ('box_name', models.CharField(max_length=3, verbose_name='Nomeclatura')),
                ('box_message', models.TextField(verbose_name='Mensagem')),
                ('capture_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Captura')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Edicao')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data Insercao')),
                ('fk_car_boxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CarsBoxes', verbose_name='Box')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro')),
            ],
            options={
                'verbose_name_plural': 'CarsBoxesMessages',
                'db_table': 'cars_boxes_message',
            },
        ),
    ]
