# Generated by Django 3.0.1 on 2020-02-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('pk_cars', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Carro')),
                ('dsc_car', models.CharField(max_length=50, verbose_name='Descrição')),
                ('factory_serial', models.CharField(max_length=64, verbose_name='Núm. Serial')),
                ('date_factory', models.DateTimeField(verbose_name='Data Fabr.')),
                ('date_insert', models.DateTimeField(auto_now=True, verbose_name='Data Inserção')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarsBoxes',
            fields=[
                ('pk_carboxes', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do Box')),
                ('box_name', models.CharField(max_length=30, verbose_name='Nome do Box')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cars', verbose_name='Carro')),
            ],
            options={
                'db_table': 'cars_boxes',
            },
        ),
    ]
