# Generated by Django 3.0.1 on 2020-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsboxes',
            name='fisical_box_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Caçamba'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Volume Máx.'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Peso Máx.'),
        ),
    ]
