# Generated by Django 3.0.1 on 2020-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carsboxes',
            options={'verbose_name_plural': 'CarsBoxes'},
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='box_name',
            field=models.CharField(max_length=30, verbose_name='Código do Box'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='pk_carboxes',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
