# Generated by Django 3.0.1 on 2020-02-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200221_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsboxes',
            name='pk_carsboxes',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Código do Carro'),
        ),
    ]
