# Generated by Django 3.0.1 on 2020-02-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200205_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsboxes',
            name='box',
            field=models.SmallIntegerField(default=1, verbose_name='Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsboxes',
            name='fisical_box_id',
            field=models.CharField(default=1, max_length=20, verbose_name='Código da Caçamba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsboxes',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='Nível'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsboxes',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='carsboxes',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='pk_carboxes',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
