# Generated by Django 3.0.1 on 2020-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200221_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsboxes',
            name='box_name',
            field=models.CharField(max_length=30, verbose_name='Nome do Box'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='pk_carsboxes',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Código do Box'),
        ),
    ]
