# Generated by Django 3.0.1 on 2020-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200226_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsboxes',
            name='charge_key',
            field=models.TextField(blank=True, null=True, verbose_name='Carga Vinculada'),
        ),
        migrations.AlterField(
            model_name='carsboxes',
            name='pk_carsboxes',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Identificação'),
        ),
    ]
