# Generated by Django 3.0.1 on 2020-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200303_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHosts',
            fields=[
                ('pk_api_hosts', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_host', models.CharField(max_length=50, verbose_name='Descrição')),
                ('type_net', models.SmallIntegerField(choices=[(0, 'LAN'), (1, 'WAN')], default=0, verbose_name='Tipo NET')),
                ('address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP')),
                ('port', models.IntegerField(default=5180, verbose_name='Porta')),
                ('flag_active', models.SmallIntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=0, verbose_name='Ativo')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Data Inserção')),
            ],
            options={
                'verbose_name_plural': 'icity_hosts',
                'db_table': 'icity_hosts',
            },
        ),
    ]
