# Generated by Django 3.0.1 on 2020-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200306_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apihosts',
            name='pk_api_hosts',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
