# Generated by Django 3.0.1 on 2019-12-31 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOperation',
            fields=[
                ('fk_users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('flag_tuser', models.SmallIntegerField(choices=[(0, 'Usuário do Sistema'), (1, 'Gerente de Departamento'), (2, 'Supervisor do Departamento'), (3, 'Conferente'), (4, 'Coletor de Mercadorias')], verbose_name='Código')),
                ('biometric_id', models.BinaryField(verbose_name='Biometria')),
            ],
        ),
    ]
