# Generated by Django 3.0.1 on 2020-02-21 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOperatorsPermissions',
            fields=[
                ('pk_user_permissions', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='User-Permisson')),
                ('codlinhasepar', models.CharField(max_length=2, verbose_name='Linha de Separação')),
                ('desclinhasepar', models.CharField(max_length=50, verbose_name='Descrição')),
                ('indseparacao', models.CharField(max_length=1, verbose_name='descrição')),
                ('ls_status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.CreateModel(
            name='UsersOperators',
            fields=[
                ('fk_users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Código')),
                ('user_integration', models.IntegerField(default=1, verbose_name='Código')),
                ('flag_tuser', models.SmallIntegerField(choices=[(0, 'Usuário do Sistema'), (1, 'Gerente de Departamento'), (2, 'Supervisor do Departamento'), (3, 'Conferente'), (4, 'Produtivo')], verbose_name='Tipo')),
                ('biometric_id', models.BinaryField(blank=True, null=True, verbose_name='Biometria')),
                ('nroempresa', models.IntegerField(verbose_name='Empresa')),
                ('tipprodutivo', models.CharField(choices=[('I', 'Inativo'), ('A', 'Ativo')], default='S', max_length=1, verbose_name='Status')),
                ('statusprodutivo', models.CharField(choices=[('S', 'Separador'), ('M', 'Movimentador'), ('C', 'Conferente')], default='S', max_length=1, verbose_name='Tipo Função')),
                ('inddisponibilidade', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Disponível')),
                ('horinijornada', models.TimeField(verbose_name='Hora início')),
                ('horfimjornada', models.TimeField(verbose_name='Hora Fim')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Inserção')),
                ('fk_cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Cars', verbose_name='Carro Alocado')),
            ],
            options={
                'db_table': 'user_operators',
            },
        ),
    ]
