# Generated by Django 3.0.1 on 2020-01-02 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersoperation',
            name='user_integration',
            field=models.IntegerField(default=1, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersoperation',
            name='biometric_id',
            field=models.BinaryField(blank=True, null=True, verbose_name='Biometria'),
        ),
        migrations.AlterField(
            model_name='usersoperation',
            name='fk_users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersoperation',
            name='flag_tuser',
            field=models.SmallIntegerField(choices=[(0, 'Usuário do Sistema'), (1, 'Gerente de Departamento'), (2, 'Supervisor do Departamento'), (3, 'Conferente'), (4, 'Produtivo')], verbose_name='Tipo'),
        ),
    ]
