# Generated by Django 3.0.1 on 2020-03-06 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersoperatorspermissions',
            old_name='desclinhasepar',
            new_name='dsc_line',
        ),
        migrations.RemoveField(
            model_name='usersoperatorspermissions',
            name='codlinhasepar',
        ),
        migrations.RemoveField(
            model_name='usersoperatorspermissions',
            name='indseparacao',
        ),
        migrations.RemoveField(
            model_name='usersoperatorspermissions',
            name='ls_status',
        ),
        migrations.AddField(
            model_name='usersoperatorspermissions',
            name='fk_users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='usersoperatorspermissions',
            name='flag_separation',
            field=models.CharField(default='R', max_length=1, verbose_name='Separação'),
        ),
        migrations.AddField(
            model_name='usersoperatorspermissions',
            name='flag_status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='usersoperatorspermissions',
            name='type_line',
            field=models.CharField(choices=[('AG', 'Alimetício Grandeza'), ('BF', 'Fardarias Grandeza'), ('BG', 'Bebidas Grandeza'), ('CO', 'Confinado'), ('FA', 'Fracionado Alimento'), ('FB', 'Fracionado Bebidas'), ('FF', 'Leveza Papel Higiênico'), ('FG', 'Fracionado Gerais'), ('FL', 'Leveza Fardaria Randeza'), ('LA', 'Licitação Alimento'), ('LF', 'Limpeza Fracionada'), ('LG', 'Limpeza Grandeza'), ('LL', 'Leveza Limpeza Grandeza')], default='Lf', max_length=2, verbose_name='Linha de Separação'),
        ),
    ]
