# Generated by Django 3.0.1 on 2020-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200306_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersoperatorspermissions',
            name='type_line',
            field=models.CharField(choices=[('AG', 'Alimetício Grandeza'), ('BF', 'Fardarias Grandeza'), ('BG', 'Bebidas Grandeza'), ('CO', 'Confinado'), ('FA', 'Fracionado Alimento'), ('FB', 'Fracionado Bebidas'), ('FF', 'Leveza Papel Higiênico'), ('FG', 'Fracionado Gerais'), ('FL', 'Leveza Fardaria Grandeza'), ('LA', 'Licitação Alimento'), ('LF', 'Limpeza Fracionada'), ('LG', 'Limpeza Grandeza'), ('LL', 'Leveza Limpeza Grandeza')], default='LF', max_length=2, verbose_name='Linha de Separação'),
        ),
    ]
