# Generated by Django 3.0.1 on 2020-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200205_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersoperatorspermissions',
            name='fk_users',
        ),
        migrations.AlterField(
            model_name='usersoperatorspermissions',
            name='pk_user_permissions',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='User-Permisson'),
        ),
    ]
